### ISSUE TITLE
Document Security**

### ISSUE THREAD

**Issue by mmilutinovic1313** [LRNWebComponents/socket-project#16]
# Firstly, please don't list any potential vulnerabilities relating to elms itself on github directly - if you find something that is out of place, shoot an email or post internally in slack.

There are two security and risk angles I was thinking we could look at in regard to our final analysis. First - we are using socket.io. Since socket relies on node, look up any problems we could run into using node (such as someone deleting a dependency and breaking the internet ;) ) and report these findings in our documentation. 

Second - The module in #15 that @btopro and @heyMP built for webcomponents is technically not up to drupal.org's security standards. See if we can figure out what their security standards are and make recommendations on how they could get the webcomponents module up to meeting these standards. This may be helpful in their processes later and relates to our socket module for when we eventually push up our prototype to the project itself.

**Comment by mmilutinovic1313** [comment]
Here is their security advisory policy - we can discuss this in the standards section of the document that we provide for class. Our webapp does not need to meet these standards in its prototype stage, but researching this may give Bryan and Potter an easy guide if they want to follow the recommended standards. 

https://www.drupal.org/security-advisory-policy

**Comment by btopro** [comment]
ummm.... @mmilutinovic1313 what do you mean it's not up to security standards? If you mean the message on drupal.org that's cause it doesn't have a full release. D.o. team won't remove that message until there is a 1.0 level release of a module

**Comment by mmilutinovic1313** [comment]
@btopro -- Even just that. We needed to cite a few standards to go base some of our decisions off of for the write-up. Do you have any standards that elms follows or that should be considered for this chat app? I know elms does a lot with accessibility on the project in general

**Comment by ChuckPwn25** [comment]
Would a link to a Websocket protocol doc help? https://tools.ietf.org/html/rfc6455#section-1.6

**Comment by btopro** [comment]
@mmilutinovic1313 hmm... ok, well what you could do is validate that it's ready for a full release. I fixed the 1 thing recently blocking a fuller release. If you ran it through https://www.drupal.org/project/coder and https://www.drupal.org/project/coder_tough_love then we'd have the evidence you are looking for w/ ability to supply the patches to accomplish it.

we follow the standards supported by the community (and validated by these modules) but I haven't done a formal audit via those modules in a long time. To test - spin up a blank drupal site w/ webcomponent modules enabled and coder / coder tough love on the same site. Then find the coder UI and run the tests. It'll give you feedback of different kinds. And yes, tough love is a pain in the butt, gives insane feedback like "try to make words lower case" level stringentness but it helps w/ readability as well.

**Comment by mmilutinovic1313** [comment]
@btopro I think this is a good idea. We can add this to our list for things to look into.

**Comment by mmilutinovic1313** [comment]
Closing
